In [2]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv(r"C:\Users\pamru\Downloads\archive (4)\Online_Courses.csv")

In [5]:
df.head()

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills,...,Course Short Intro,Weekly study,Premium course,What's include,Rank,Created by,Program,Number of ratings,Price,COURSE CATEGORIES
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Launch your career in data science. Gain found...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Relational Database Management S...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Build the Foundation for your Data Science car...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Github, Python Programming, Jupy...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Key Technologies for Business Specialization,https://www.coursera.org/specializations/key-t...,Get Ahead with Key Business Technologies. Gain...,Business,Business Essentials,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Artificial Intelligence (AI), Bu...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Deep Learning Specialization,https://www.coursera.org/specializations/deep-...,Become a Machine Learning expert. Master the f...,Data Science,Machine Learning,Specialization,English,"Subtitles: English, Chinese (Traditional), Ara...","Artificial Neural Network, Convolutional Neura...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.shape

(8092, 45)

In [7]:
df.head()

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills,...,Course Short Intro,Weekly study,Premium course,What's include,Rank,Created by,Program,Number of ratings,Price,COURSE CATEGORIES
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Launch your career in data science. Gain found...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Relational Database Management S...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Build the Foundation for your Data Science car...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Github, Python Programming, Jupy...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,Key Technologies for Business Specialization,https://www.coursera.org/specializations/key-t...,Get Ahead with Key Business Technologies. Gain...,Business,Business Essentials,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Artificial Intelligence (AI), Bu...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Deep Learning Specialization,https://www.coursera.org/specializations/deep-...,Become a Machine Learning expert. Master the f...,Data Science,Machine Learning,Specialization,English,"Subtitles: English, Chinese (Traditional), Ara...","Artificial Neural Network, Convolutional Neura...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Show rows where NaN columns are present
nan_columns_per_row = df.isna().apply(lambda row: row[row].index.tolist(), axis=1)
nan_columns_per_row = nan_columns_per_row[nan_columns_per_row.str.len() > 0]

# Display the result for rows with NaNs
print(nan_columns_per_row)
nan_columns_per_row.shape

0       [Program Type, Courses, Level, Number of Revie...
1       [Program Type, Courses, Level, Number of Revie...
2       [Program Type, Courses, Level, Number of Revie...
3       [Program Type, Courses, Level, Number of Revie...
4       [Program Type, Courses, Level, Number of Revie...
                              ...
8087    [Category, Sub-Category, Course Type, Language...
8088    [Short Intro, Category, Sub-Category, Course T...
8089    [Category, Sub-Category, Course Type, Language...
8090    [Category, Sub-Category, Course Type, Language...
8091    [Category, Sub-Category, Course Type, Language...
Length: 8092, dtype: object

(8092,)

In [9]:
# Display column headings (names)
print(df.columns)

Index(['Unnamed: 0', 'Title', 'URL', 'Short Intro', 'Category', 'Sub-Category',
       'Course Type', 'Language', 'Subtitle Languages', 'Skills',
       'Instructors', 'Rating', 'Number of viewers', 'Duration', 'Site',
       'Program Type', 'Courses', 'Level', 'Number of Reviews',
       'Unique Projects', 'Prequisites', 'What you learn', 'Related Programs',
       'Monthly access', '6-Month access', '4-Month access', '3-Month access',
       '5-Month access', '2-Month access', 'School', 'Topics related to CRM',
       'ExpertTracks', 'FAQs', 'Course Title', 'Course URL',
       'Course Short Intro', 'Weekly study', 'Premium course',
       'What's include', 'Rank', 'Created by', 'Program', 'Number of ratings',
       'Price', 'COURSE CATEGORIES'],
      dtype='object')

In [10]:
# Check for columns with NaN values
nan_columns = df.columns[df.isna().any()].tolist()
print(nan_columns)

['Short Intro', 'Category', 'Sub-Category', 'Course Type', 'Language', 'Subtitle Languages', 'Skills', 'Instructors', 'Rating', 'Number of viewers', 'Duration', 'Program Type', 'Courses', 'Level', 'Number of Reviews', 'Unique Projects', 'Prequisites', 'What you learn', 'Related Programs', 'Monthly access', '6-Month access', '4-Month access', '3-Month access', '5-Month access', '2-Month access', 'School', 'Topics related to CRM', 'ExpertTracks', 'FAQs', 'Course Title', 'Course URL', 'Course Short Intro', 'Weekly study', 'Premium course', "What's include", 'Rank', 'Created by', 'Program', 'Number of ratings', 'Price', 'COURSE CATEGORIES']

In [11]:
# Select the first 5 columns of the DataFrame
df_first_5_cols = df.iloc[:, :10]

# Check the updated DataFrame
print(df_first_5_cols.head())
df=df_first_5_cols
df.head()

   Unnamed: 0                                              Title  \
0           0                    Machine Learning Specialization
1           1        Introduction to Data Science Specialization
2           2  Data Science Fundamentals with Python and SQL ...
3           3       Key Technologies for Business Specialization
4           4                       Deep Learning Specialization

                                                 URL  \
0  https://www.coursera.org/specializations/machi...
1  https://www.coursera.org/specializations/intro...
2  https://www.coursera.org/specializations/data-...
3  https://www.coursera.org/specializations/key-t...
4  https://www.coursera.org/specializations/deep-...

                                         Short Intro      Category  \
0  #BreakIntoAI with Machine Learning Specializat...  Data Science
1  Launch your career in data science. Gain found...  Data Science
2  Build the Foundation for your Data Science car...  Data Science
3  Get Ahead with Key Business Technologies. Gain...      Business
4  Become a Machine Learning expert. Master the f...  Data Science

          Sub-Category     Course Type Language  \
0     Machine Learning  Specialization  English
1        Data Analysis  Specialization  English
2        Data Analysis  Specialization  English
3  Business Essentials  Specialization  English
4     Machine Learning  Specialization  English

                                  Subtitle Languages  \
0                                 Subtitles: English
1  Subtitles: English, Arabic, French, Portuguese...
2  Subtitles: English, Arabic, French, Portuguese...
3  Subtitles: English, Arabic, French, Portuguese...
4  Subtitles: English, Chinese (Traditional), Ara...

                                              Skills
0  Decision Trees, Artificial Neural Network, Log...
1  Data Science, Relational Database Management S...
2  Data Science, Github, Python Programming, Jupy...
3  Data Science, Artificial Intelligence (AI), Bu...
4  Artificial Neural Network, Convolutional Neura...

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log..."
1,1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Launch your career in data science. Gain found...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Relational Database Management S..."
2,2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Build the Foundation for your Data Science car...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Github, Python Programming, Jupy..."
3,3,Key Technologies for Business Specialization,https://www.coursera.org/specializations/key-t...,Get Ahead with Key Business Technologies. Gain...,Business,Business Essentials,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Artificial Intelligence (AI), Bu..."
4,4,Deep Learning Specialization,https://www.coursera.org/specializations/deep-...,Become a Machine Learning expert. Master the f...,Data Science,Machine Learning,Specialization,English,"Subtitles: English, Chinese (Traditional), Ara...","Artificial Neural Network, Convolutional Neura..."

In [12]:
df.isna()

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8087,False,False,False,False,True,True,True,True,True,True
8088,False,False,False,True,True,True,True,True,True,True
8089,False,False,False,False,True,True,True,True,True,True
8090,False,False,False,False,True,True,True,True,True,True
8091,False,False,False,False,True,True,True,True,True,True

In [13]:
# Consider only the first 1000 rows
df_first_1000 = df.iloc[:1000]

# Check for NaN values in these rows
df=df_first_1000
df

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log..."
1,1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Launch your career in data science. Gain found...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Relational Database Management S..."
2,2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Build the Foundation for your Data Science car...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Github, Python Programming, Jupy..."
3,3,Key Technologies for Business Specialization,https://www.coursera.org/specializations/key-t...,Get Ahead with Key Business Technologies. Gain...,Business,Business Essentials,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Artificial Intelligence (AI), Bu..."
4,4,Deep Learning Specialization,https://www.coursera.org/specializations/deep-...,Become a Machine Learning expert. Master the f...,Data Science,Machine Learning,Specialization,English,"Subtitles: English, Chinese (Traditional), Ara...","Artificial Neural Network, Convolutional Neura..."
...,...,...,...,...,...,...,...,...,...,...
995,995,ChatGPT for Beginners: SciFi Writing with Dall-e,https://www.coursera.org/projects/chatgpt-dall...,Critical Thinking,Computer Science,Algorithms,Project,English,NaN,"Critical Thinking,Creative Writing,AI communic..."
996,996,Curso Completo de Power BI Desktop,https://www.coursera.org/projects/curso-comple...,Conocer el funcionamiento de Power BI Desktop,Data Science,Data Analysis,Project,Spanish,NaN,NaN
997,997,Excel for Beginners: Pivot Tables,https://www.coursera.org/projects/excel-for-be...,Format data generated from the pivot tables in...,Business,Business Essentials,Project,English,NaN,"Spreadsheet,Microsoft Excel,"
998,998,Cloud SQL for MySQL: Qwik Start,https://www.coursera.org/learn/googlecloud-clo...,SQL Operations,Data Science,Data Analysis,Project,English,NaN,"MySQL,cloud sql,SQL Operations,"
999,999,Migrating to Cloud SQL from Amazon RDS for MyS...,https://www.coursera.org/learn/googlecloud-mig...,This is a self-paced lab that takes place in t...,Information Technology,Cloud Computing,Project,English,NaN,"Database (DBMS),Google Cloud Platform,MySQL,"

In [14]:
df.isna()

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,True,False
996,False,False,False,False,False,False,False,False,True,True
997,False,False,False,False,False,False,False,False,True,False
998,False,False,False,False,False,False,False,False,True,False
999,False,False,False,False,False,False,False,False,True,False

In [15]:
df_cleaned = df.dropna(subset=['Subtitle Languages'])
df=df_cleaned

In [16]:
df

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log..."
1,1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Launch your career in data science. Gain found...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Relational Database Management S..."
2,2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Build the Foundation for your Data Science car...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Github, Python Programming, Jupy..."
3,3,Key Technologies for Business Specialization,https://www.coursera.org/specializations/key-t...,Get Ahead with Key Business Technologies. Gain...,Business,Business Essentials,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Artificial Intelligence (AI), Bu..."
4,4,Deep Learning Specialization,https://www.coursera.org/specializations/deep-...,Become a Machine Learning expert. Master the f...,Data Science,Machine Learning,Specialization,English,"Subtitles: English, Chinese (Traditional), Ara...","Artificial Neural Network, Convolutional Neura..."
...,...,...,...,...,...,...,...,...,...,...
987,987,Data Science Math Skills,https://www.coursera.org/learn/datasciencemath...,Data science courses contain math—no avoiding ...,Math and Logic,Math and Logic,Course,English,"Subtitles: Arabic, French, Portuguese (Europea...","Bayes' Theorem,Bayesian Probability,Probabilit..."
988,988,Global Financing Solutions (by EDHEC and Soci...,https://www.coursera.org/learn/global-financin...,The MOOC Global Financing Solutions is your on...,Business,Finance,Course,English,"Subtitles: French, Portuguese (European), Russ...","Syndication,project finance,Capital Market,Acq..."
989,989,React Basics,https://www.coursera.org/learn/react-basics,React is a powerful JavaScript library that yo...,Computer Science,Mobile and Web Development,Course,English,Subtitles: English,"Web Application,Front-End Web Development,Reac..."
990,990,Probabilistic Graphical Models 1: Representation,https://www.coursera.org/learn/probabilistic-g...,Probabilistic graphical models (PGMs) are a ri...,Data Science,Machine Learning,Course,English,"Subtitles: Arabic, French, Portuguese (Europea...","Bayesian Network,Graphical Model,Markov Random..."
991,991,Introduction to Enterprise Computing,https://www.coursera.org/learn/introduction-en...,Large Scale Enterprise Computing powers all ma...,Information Technology,Cloud Computing,Course,English,"Subtitles: Arabic, French, Portuguese (Europea...","Mainframe,z/OS,Enterprise Software,security,IB..."

In [17]:
df.isna()

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
987,False,False,False,False,False,False,False,False,False,False
988,False,False,False,False,False,False,False,False,False,False
989,False,False,False,False,False,False,False,False,False,False
990,False,False,False,False,False,False,False,False,False,False
991,False,False,False,False,False,False,False,False,False,False

In [18]:
df=df.dropna()

In [19]:
df.shape

(771, 10)

In [20]:
df

,Unnamed: 0,Title,URL,Short Intro,Category,Sub-Category,Course Type,Language,Subtitle Languages,Skills
0,0,Machine Learning Specialization,https://www.coursera.org/specializations/machi...,#BreakIntoAI with Machine Learning Specializat...,Data Science,Machine Learning,Specialization,English,Subtitles: English,"Decision Trees, Artificial Neural Network, Log..."
1,1,Introduction to Data Science Specialization,https://www.coursera.org/specializations/intro...,Launch your career in data science. Gain found...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Relational Database Management S..."
2,2,Data Science Fundamentals with Python and SQL ...,https://www.coursera.org/specializations/data-...,Build the Foundation for your Data Science car...,Data Science,Data Analysis,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Github, Python Programming, Jupy..."
3,3,Key Technologies for Business Specialization,https://www.coursera.org/specializations/key-t...,Get Ahead with Key Business Technologies. Gain...,Business,Business Essentials,Specialization,English,"Subtitles: English, Arabic, French, Portuguese...","Data Science, Artificial Intelligence (AI), Bu..."
4,4,Deep Learning Specialization,https://www.coursera.org/specializations/deep-...,Become a Machine Learning expert. Master the f...,Data Science,Machine Learning,Specialization,English,"Subtitles: English, Chinese (Traditional), Ara...","Artificial Neural Network, Convolutional Neura..."
...,...,...,...,...,...,...,...,...,...,...
987,987,Data Science Math Skills,https://www.coursera.org/learn/datasciencemath...,Data science courses contain math—no avoiding ...,Math and Logic,Math and Logic,Course,English,"Subtitles: Arabic, French, Portuguese (Europea...","Bayes' Theorem,Bayesian Probability,Probabilit..."
988,988,Global Financing Solutions (by EDHEC and Soci...,https://www.coursera.org/learn/global-financin...,The MOOC Global Financing Solutions is your on...,Business,Finance,Course,English,"Subtitles: French, Portuguese (European), Russ...","Syndication,project finance,Capital Market,Acq..."
989,989,React Basics,https://www.coursera.org/learn/react-basics,React is a powerful JavaScript library that yo...,Computer Science,Mobile and Web Development,Course,English,Subtitles: English,"Web Application,Front-End Web Development,Reac..."
990,990,Probabilistic Graphical Models 1: Representation,https://www.coursera.org/learn/probabilistic-g...,Probabilistic graphical models (PGMs) are a ri...,Data Science,Machine Learning,Course,English,"Subtitles: Arabic, French, Portuguese (Europea...","Bayesian Network,Graphical Model,Markov Random..."
991,991,Introduction to Enterprise Computing,https://www.coursera.org/learn/introduction-en...,Large Scale Enterprise Computing powers all ma...,Information Technology,Cloud Computing,Course,English,"Subtitles: Arabic, French, Portuguese (Europea...","Mainframe,z/OS,Enterprise Software,security,IB..."

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Assuming df_cleaned is your dataset with relevant columns ('Skills', 'URL', 'Category', 'Sub-Category')

# Create a TfidfVectorizer to convert the 'Skills' text into numerical vectors
vectorizer = TfidfVectorizer(stop_words='english')

# Fit and transform the Skills column
skills_matrix = vectorizer.fit_transform(df['Skills'])

# Function to get recommendations based on user input
def recommend_courses(user_input):
    # Transform the user input into the same vector space as the skills data
    user_vector = vectorizer.transform([user_input])
    
    # Calculate cosine similarity between the user input and the courses' skills
    cosine_similarities = cosine_similarity(user_vector, skills_matrix)
    
    # Get the top 5 matching courses based on similarity scores
    top_indexes = cosine_similarities[0].argsort()[-5:][::-1]
    
    # Retrieve URLs, categories, and sub-categories for the top 5 courses
    recommended_courses = df.iloc[top_indexes][['Title','URL']]
    
    return recommended_courses

# Example: Get recommendations for a given skill input
user_input = "AI"
recommended_courses = recommend_courses(user_input)
print(recommended_courses)

                                                 Title  \
648                                    AI For Everyone
700       Introduction to Artificial Intelligence (AI)
30                      AI For Business Specialization
214  Digital Manufacturing & Design Technology  Spe...
952  Introduction to Computer Vision and Image Proc...

                                                   URL
648     https://www.coursera.org/learn/ai-for-everyone
700  https://www.coursera.org/learn/introduction-to-ai
30   https://www.coursera.org/specializations/ai-fo...
214  https://www.coursera.org/specializations/digit...
952  https://www.coursera.org/learn/introduction-co...

In [22]:
recommended_courses

,Title,URL
648,AI For Everyone,https://www.coursera.org/learn/ai-for-everyone
700,Introduction to Artificial Intelligence (AI),https://www.coursera.org/learn/introduction-to-ai
30,AI For Business Specialization,https://www.coursera.org/specializations/ai-fo...
214,Digital Manufacturing & Design Technology Spe...,https://www.coursera.org/specializations/digit...
952,Introduction to Computer Vision and Image Proc...,https://www.coursera.org/learn/introduction-co...

In [30]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pickle

# Function to load dataset from a file path
def load_dataset(file_path):
    """
    Function to load dataset from a CSV or other file format into a pandas DataFrame.
    Assumes the dataset has columns 'Skills', 'Title', and 'URL'.
    """
    df = pd.read_csv(file_path)

    # Replace NaN values in the 'Skills' column with an empty string
    df['Skills'] = df['Skills'].fillna('')

    return df

# Function to train and save the model
def train_and_save_model(df):
    """
    Function to train the TfidfVectorizer model on the 'Skills' column and save it to a pickle file.
    """
    vectorizer = TfidfVectorizer(stop_words='english')
    skills_matrix = vectorizer.fit_transform(df['Skills'])

    # Save the vectorizer to a pickle file for later use
    with open("tfidf_vectorizer.pkl", 'wb') as f:
        pickle.dump(vectorizer, f)

    return vectorizer, skills_matrix

# Function to get course recommendations based on user input
def recommend_courses(user_input, vectorizer, skills_matrix, df):
    """
    Function to predict course recommendations based on user input.
    Returns the top 5 courses based on cosine similarity.
    """
    # Transform the user input into the same vector space as the skills data
    user_vector = vectorizer.transform([user_input])

    # Calculate cosine similarity between the user input and the courses' skills
    cosine_similarities = cosine_similarity(user_vector, skills_matrix)

    # Get the top 5 matching courses based on similarity scores
    top_indexes = cosine_similarities[0].argsort()[-5:][::-1]

    # Retrieve Titles, URLs for the top 5 courses
    recommended_courses = df.iloc[top_indexes][['Title', 'URL']]

    return recommended_courses

# Main logic
if __name__ == "__main__":
    # Load the dataset from the provided file path
    file_path = r"C:\Users\pamru\Downloads\archive (4)\Online_Courses.csv"  # Replace with your actual file path
    df = load_dataset(file_path)

    # Check if model already exists; if not, train and save it
    try:
        with open("tfidf_vectorizer.pkl", 'rb') as f:
            vectorizer = pickle.load(f)
        skills_matrix = vectorizer.transform(df['Skills'])
        print("Successfully loaded pre-trained vectorizer.")
    except FileNotFoundError:
        print("No pre-trained vectorizer found, training a new one.")
        vectorizer, skills_matrix = train_and_save_model(df)

    # Example: Get recommendations for a given skill input
    user_input = "AI, deep learning, neural networks"
    recommended_courses = recommend_courses(user_input, vectorizer, skills_matrix, df)

    print("Recommended Courses:")
    print(recommended_courses)

No pre-trained vectorizer found, training a new one.
Recommended Courses:
                                                  Title  \
898   Introduction to Deep Learning & Neural Network...
3024                                      Deep Learning
2996                Artificial Intelligence for Trading
2366       Introduction to Artificial Intelligence (AI)
2787       Introduction to Artificial Intelligence (AI)

                                                    URL
898   https://www.coursera.org/learn/introduction-to...
3024  https://www.udacity.com/course/deep-learning-n...
2996  https://www.udacity.com/course/ai-for-trading-...
2366  https://www.coursera.org/learn/introduction-to...
2787  https://www.coursera.org/learn/introduction-to...